(cl:defpackage robotclient-srv
  (:use )
  (:export
   "ROTATEROBOT"
   "<ROTATEROBOT-REQUEST>"
   "ROTATEROBOT-REQUEST"
   "<ROTATEROBOT-RESPONSE>"
   "ROTATEROBOT-RESPONSE"
   "MOVEROBOT"
   "<MOVEROBOT-REQUEST>"
   "MOVEROBOT-REQUEST"
   "<MOVEROBOT-RESPONSE>"
   "MOVEROBOT-RESPONSE"
   "GETCOORD"
   "<GETCOORD-REQUEST>"
   "GETCOORD-REQUEST"
   "<GETCOORD-RESPONSE>"
   "GETCOORD-RESPONSE"
   "UPDATETWIST"
   "<UPDATETWIST-REQUEST>"
   "UPDATETWIST-REQUEST"
   "<UPDATETWIST-RESPONSE>"
   "UPDATETWIST-RESPONSE"
  ))

